### PR TITLE
Replace the custom event with eawsy/aws-lambda-go-net

### PR DESCRIPTION
**Pull request by cristim**
The PR contains the following changes:

- The golang handler example was modified to use eawsy/aws-lambda-go-net  instead of a custom event
- The handler now also creates a custom HTTP header in the response to showcase header handling, fixing #2
- Build system cleanups and simplifications, reusing the upstream Makefile with minimal changes
- The function invocation uses curl instead of sls invoke, for end-to-end visibility
- Markdown lint fixes of the README.md

### CODE REVIEW

**Comment by yunspace** [comment]
Hi sorry didn't get notification for this PR for some reason. Will take a look at merge!

**Comment by yunspace** [comment]
@cristim thanks for the PR, very comprehensive. My initial thought is that we should probably keep both `aws-lambda-go-shim` and `aws-lambda-go-net` in parallel. 

For example, in my use case I'm actually using Kinesis directly as an event source, so I don't sit behind a API Gateway. Thus I don't I need  HTTP support nor custom headers. So the standard `go-shim` will work fine for my case. Where as for #2 it would make sense to use `go-net`

I will make some slight modifications if you don't mind and merge this in.

**Comment by cristim** [comment]
Sure, feel free to change it

**Comment by cristim** [comment]
@yunspace I think it would be better to have multiple examples included as part of a single serverless project, each built with its own event source and based on its respective library.

What do you think?

**Comment by yunspace** [comment]
@cristim yes I feel that's exactly what we need. I've created a `lambda-go-shim` branch for now and will rebase your PR into master. Tomorrow I will look at splitting out the 2 examples.

**Pull request merged**
